# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
google: &google
  google_client_id: <%= ENV["MATERIAL_BOOKS_GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["MATERIAL_BOOKS_GOOGLE_CLIENT_SECRET"] %>

twitter: &twitter
  twitter_consumer_key: <%= ENV["MATERIAL_BOOKS_TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["MATERIAL_BOOKS_TWITTER_CONSUMER_SECRET"] %>

facebook: &facebook
  facebook_app_id: <%= ENV["MATERIAL_BOOKS_FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["MATERIAL_BOOKS_FACEBOOK_APP_SECRET"] %>

development:
  secret_key_base: a51855798915336fb01c2e6a000e4b04e696d4bb3a2199748aa6a5184d58feea125cee0a5a3c4b321b63364e47b8c672bb745f8e31287f3af895ebf2e4139855
  <<: *google
  <<: *twitter
  <<: *facebook

test:
  secret_key_base: cc89a9f727abb905f31b1e88102ad0d2c8a56cc8a4404c00b793cf828457d346f22706ce837bb97c21d72f05abf96ac4add1f7d56825c2332936858adc0ed3f2
  <<: *google
  <<: *twitter
  <<: *facebook

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *google
  <<: *twitter
  <<: *facebook
